name: Run OFPPT Script

on:
  schedule:
    - cron: '0 */6 * * *'  # تشغيل الأكشن كل ساعة
  workflow_dispatch:  # السماح بالتشغيل اليدوي عند الحاجة

concurrency:
  group: ofppt-script  # منع تشغيل الأكشن مرتين في نفس الوقت
  cancel-in-progress: true  # إلغاء العملية الجارية إذا بدأت جديدة

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # تنزيل الكود من المستودع

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # اختيار إصدار Python

      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium undetected-chromedriver webdriver-manager

      - name: Run the script
        run: python main.py  # تشغيل السكربت
